version: '3.8'

networks:
  datasus_net:
    name: datasus_net

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_datasus
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:z
    networks:
      - datasus_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${DB_PASSWORD}"]
      timeout: 20s
      retries: 10

  n8n:
    build:
      context: .
      dockerfile: docker/n8n.Dockerfile
    container_name: n8n_datasus
    user: "root"
    privileged: true
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=America/Campo_Grande
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dados_datasus:/data:z
      - ./scripts:/scripts:z
      - ./.env:/.env:ro
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - datasus_net

  python-consolidador:
    image: ghcr.io/delarissag/python-consolidador:latest
    env_file:
      - .env
    volumes:
      - ./dados_datasus:/data:z
      - ./scripts:/scripts:z
    networks:
      - datasus_net

volumes:
  mysql_data:
  n8n_data:
